### PR TITLE
Update to use shared model class from `osu.Game`

### PR DESCRIPTION
**Pull request by peppy**
Resolves https://github.com/ppy/osu-queue-score-statistics/issues/13

- [x] Depends on ppy/osu#19082.

### CODE REVIEW

**Comment by peppy** [comment]
I haven't heavily tested this at runtime yet. Will do so over the coming days (will use it to re-run some imports at least).

**Comment by smoogipoo** [comment]
Need to go through this with a fine comb. Things like this will fail (I believe): https://github.com/ppy/osu-queue-score-statistics/blob/f288bd7abbe8d29fa2fe07968b1d0ef0e21230f3/osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs#L45

It's also why I advocate to use
```
new
{
    X = score.X
}
```
At all times in our queries.

**Comment by peppy** [comment]
yeah, it's a valid concern.

**Review by smoogipoo — APPROVED** [review]
I think this should be fine. Also haven't tested but can try to in the next ~2 hours.

**Review by smoogipoo — APPROVED** [review]
It seems to be okay.

**Pull request merged**
