### PR TITLE
Import `has_replay` and `legacy_score_id` into solo scores

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu/pull/20070

Resolves https://github.com/ppy/osu-queue-score-statistics/issues/70

```
mysql> select * from osu_scores_high where replay=1 limit 1;
+----------+------------+---------+--------+----------+------+---------+----------+----------+-----------+-----------+-----------+---------+--------------+---------------------+---------+--------+--------+-----------------+
| score_id | beatmap_id | user_id | score  | maxcombo | rank | count50 | count100 | count300 | countmiss | countgeki | countkatu | perfect | enabled_mods | date                | pp      | replay | hidden | country_acronym |
+----------+------------+---------+--------+----------+------+---------+----------+----------+-----------+-----------+-----------+---------+--------------+---------------------+---------+--------+--------+-----------------+
|  5230054 |      12943 |   39828 | 583841 |      274 | XH   |       0 |        0 |      116 |         0 |        35 |         0 |       1 |         1136 | 2008-10-16 04:30:01 | 31.0558 |      1 |      0 | PL              |
+----------+------------+---------+--------+----------+------+---------+----------+----------+-----------+-----------+-----------+---------+--------------+---------------------+---------+--------+--------+-----------------+
1 row in set (0.00 sec)

mysql> select * from solo_scores where data->'$.legacy_score_id' = 5230054;
+----+---------+------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+----------+---------------------+---------------------+
| id | user_id | beatmap_id | ruleset_id | data                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | has_replay | preserve | created_at          | updated_at          |
+----+---------+------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+----------+---------------------+---------------------+
| 76 |   39828 |      12943 |          0 | {"mods": [{"acronym": "DT"}, {"acronym": "SD"}, {"acronym": "FL"}, {"acronym": "HR"}], "rank": "XH", "passed": true, "user_id": 39828, "accuracy": 1.0, "build_id": null, "ended_at": "2008-10-16T04:30:01+00:00", "max_combo": 274, "beatmap_id": 12943, "has_replay": true, "ruleset_id": 0, "started_at": null, "statistics": {"great": 116}, "total_score": 300000, "legacy_score_id": 5230054, "legacy_total_score": 583841, "maximum_statistics": {"great": 116, "legacy_combo_increase": 158}} |          0 |        1 | 2008-10-16 04:30:01 | 2008-10-16 04:30:01 |
+----+---------+------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+----------+---------------------+---------------------+
1 row in set (0.21 sec)
```

### CODE REVIEW

**Comment by peppy** [comment]
Is `legacy_score_id` serialised for null cases? It probably shouldn't be if so.

**Comment by smoogipoo** [comment]
Oh, right. Good point. Will fix in https://github.com/ppy/osu/pull/20070

**Comment by smoogipoo** [comment]
It looks fine. Json.NET's default is to not serialise default values.

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
I just realised that the issue thread has `has_replay` inside the table itself, not `data`. Shall I make that change instead...?

**Comment by peppy** [comment]
Right, I missed that (presumed it was correct from reading the OP..)

It should be the column which is set, not the data.

**Pull request merged**
