### PR TITLE
Add unit testing

### PR DESCRIPTION
**Pull request by smoogipoo**
Just seeing if this works, I have no idea what state this branch is in.

### CODE REVIEW

**Comment by peppy** [comment]
I've got things to a working state here. I'm planning on doing some more work on this to tidy things up, but let's get this in as a MVP.

@smoogipoo can you check my commits and make sure it looks good to you?

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
Are the tests here actually working? Excluding the deadlocks, which as you explained to me are expected, is the following expected?
```
MySqlConnector.MySqlException (0x80004005): Duplicate entry '21' for key 'solo_scores_process_history.PRIMARY'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 136
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 458
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 282
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 101
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 452
   at MySqlAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert) in /_/Dapper.Contrib/SqlMapperExtensions.cs:line 936
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in /_/Dapper.Contrib/SqlMapperExtensions.cs:line 377
   at osu.Server.Queues.ScoreStatisticsProcessor.ScoreStatisticsProcessor.updateHistoryEntry(ScoreItem item, MySqlConnection db, MySqlTransaction transaction) in /home/runner/work/osu-queue-score-statistics/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs:line 130
   at osu.Server.Queues.ScoreStatisticsProcessor.ScoreStatisticsProcessor.ProcessResult(ScoreItem item) in /home/runner/work/osu-queue-score-statistics/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs:line 94
```

**Comment by peppy** [comment]
Well as you can see they are passing on CI, and they pass locally on many consecutive runs. Can you give more details on the failure (which test is failing; is it a specific testing order?)

The history table is cleared per test:

https://github.com/ppy/osu-queue-score-statistics/blob/64f00510796b41de8e9fdabcb1358c0534f8151d/osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs#L46

and inserted scores already have safely incrementing IDs:

https://github.com/ppy/osu-queue-score-statistics/blob/64f00510796b41de8e9fdabcb1358c0534f8151d/osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs#L59

so I'm not immediately sure how you hit this scenario...

**Comment by smoogipoo** [comment]
It's in the CI logs.

**Comment by peppy** [comment]
Aha, I see it now. May be a lower level issue with the processor itself, or something to do with concurrency.

I'll investigate this, but will look to fix it separately. I'm currently working through remaining issues like:

- Console output isn't shown in rider after test runs (so this would not be visible there)
- Exceptions thrown by the queue processor don't bubble up to tests

both of which would likely expose this failure.

Will merge this for now so I can continue to move forward without a huge merge chain.

**Pull request merged**
